# Sample Snapfile for capturing screenshots
scheme "Verse Reminder"

# Devices to run snapshot on
devices([
    "iPad Air 13-inch (M3)"
])  
languages(["en-US"])

clear_previous_screenshots(true)
erase_simulator true
