# Sample Snapfile for capturing screenshots
scheme "Verse Reminder"

# Devices to run snapshot on
devices([
  "iPhone 16 Pro",
  "iPhone 16 Pro Max",
  "iPhone 16e",
  "iPhone 16",
  "iPhone 16 Plus",
  "iPad Pro 11-inch (M4)",
  "iPad Pro 13-inch (M4)",
  "iPad mini (A17 Pro)",
  "iPad (A16)",
  "iPad Air 13-inch (M3)",
  "iPad Air 11-inch (M3)"
])

languages(["en-US"])

clear_previous_screenshots(true)
